apiVersion: v1 
kind: Service 
metadata: 
  name: ride-mongo-db-service 
  namespace: uber 
spec: 
  clusterIP: None
  selector: 
   app: ride-mongo-db 
  ports: 
   - port: 27017
     targetPort: 27017