apiVersion: v1 
kind: Secrete
metadata:
  name: ride-secret
  namespace: uber
type:  Opaque
stringData:
  JWT_SECRET: ZWY5YjE3NjQ1ODRkZjkwZWMyZDVlZDg0NWZiMjYxMjY4ZDM2NzUzMDZiNjg1ZTc2M2NkMzI3MTdlOTY2NjVkMg==
