apiVersion: v1
kind: ConfigMap
metadata:
  name: captain-config
  namespace: uber
data:
  MONGO_URL: mongodb://user-mongo-db-service:27017/userDB
  RABBIT_URL: amqp://guest:guest@rabbitmq-service:5672
  BASE_URL: http://gate-way-service:3000
