apiVersion: v1
kind: ConfigMap 
metadata:
 name: user-config
 namespace: uber
data:
  MONGO_URL: mongodb://localhost:27017/userDB
  RABBIT_URL: amqp://guest:guest@localhost:5672
  BASE_URL: http://localhost:3000
  