apiVersion:  autoscalling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: captain-app-auto-scaller
  namespace: uber
spec:
  scaleTargetRef:
     apiVersion: apps/v1 
     kind: Deployment
     name: captain-management
    
  minReplicas: 
  maxReplicas:
  metrics:
   - type: Resource 
     resource:
       name: cpu 
       target: 
         type: Utilization
         averageUtilization: 50