apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-db
  namespace: uber
spec:
  serviceName: "mongo-service"   # must match headless service
  replicas: 1                    # specify replicas, can scale later
  selector:
    matchLabels:
      app: mongo-db
  template:
    metadata:
      labels:
        app: mongo-db
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: mongo-db-container
          image: mongo:6.0           # corrected image name
          ports:
            - containerPort: 27017   # MongoDB default port
          volumeMounts:
            - name: captain-data-storage
              mountPath: /data/db   # MongoDB default data directory
  volumeClaimTemplates:
    - metadata:
        name: captain-data-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
